---
title: "Figure 3 (Circos plots)"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

```{r packages, message=FALSE}
library(grid)
library(gridExtra)
library(targets)
library(here)
# wflow_build() renders from analysis/; store path must be explicit
tgt_store <- here("_targets")
```

```{r data}
grobs <- tar_read(figure3_grobs, store = tgt_store)
circos.grobs   <- grobs$circos.grobs
ag.grobs       <- grobs$ag.grobs
rearrangements <- grobs$rearrangements
leg.list       <- grobs$leg.list
lab_id         <- grobs$lab_id
```

```{r fig3.2, fig.width=18, fig.height=12, dev=c("png", "pdf")}
m <- cbind(1, 2, 3)
grid.newpage()
vp <- viewport(x=unit(0.5, "npc"), y=unit(0.96, "npc"),
               width=unit(0.97, "npc"),
               height=unit(0.95, "npc"),
               just=c("center", "top"))
pushViewport(vp)
grid.arrange(grobs=list(circos.grobs, ag.grobs, rearrangements),
             layout_matrix=m,
             widths=c(1, 1, 1.5),
             newpage=FALSE)
grid.text(lab_id,
          x=unit(0.025, "npc"),
          y=unit(c(0.99, 0.45), "npc"),
          gp=gpar(cex=1.75), rot=0, just="left")
grid.text(lab_id[1:2],
          x=unit(0.8, "npc"),
          y=unit(c(0.98, 0.45), "npc"),
          gp=gpar(cex=1.75))
popViewport()
grid.text(letters[1:3], x=unit(c(0.02, 0.3, 0.57), "npc"),
          y=unit(rep(0.98, 3), "npc"),
          gp=gpar(cex=2.75))
vp1 <- viewport(x=unit(0.35, "npc"), y=unit(0.98, "npc"),
                width=unit(0.06, "npc"),
                height=unit(0.05, "npc"),
                just=c("left", "top"))
pushViewport(vp1)
grid.draw(leg.list[[1]])
grid.rect()
popViewport()
vp2 <- viewport(x=unit(0.35, "npc"), y=unit(0.45, "npc"),
                width=unit(0.06, "npc"),
                height=unit(0.05, "npc"),
                just=c("left", "top"))
pushViewport(vp2)
grid.draw(leg.list[[2]])
grid.rect()
popViewport()
```
